/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedReferRouteImport } from './routes/_authenticated/refer'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedRecentsRouteImport } from './routes/_authenticated/recents'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotificationPreferencesRouteImport } from './routes/_authenticated/notification-preferences'
import { Route as AuthenticatedNewJoinersRouteImport } from './routes/_authenticated/new-joiners'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedDataExportRouteImport } from './routes/_authenticated/data-export'
import { Route as AuthenticatedCreatorDashboardRouteImport } from './routes/_authenticated/creator-dashboard'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountDeleteRouteImport } from './routes/_authenticated/account-delete'
import { Route as _e2ePeerSheetBannerRouteImport } from './routes/__e2e.peer-sheet-banner'
import { Route as _e2eCallFullscreenRouteImport } from './routes/__e2e.call-fullscreen'
import { Route as _e2eCallControlsRouteImport } from './routes/__e2e.call-controls'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as Call_e2ePeerSheetBannerRouteImport } from './routes/call.__e2e.peer-sheet-banner'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AuthenticatedRoomsNewRouteImport } from './routes/_authenticated/rooms.new'
import { Route as AuthenticatedRoomsIdRouteImport } from './routes/_authenticated/rooms.$id'
import { Route as AuthenticatedMysteryCaseIdRouteImport } from './routes/_authenticated/mystery.$caseId'
import { Route as AuthenticatedMatchmakerNewRouteImport } from './routes/_authenticated/matchmaker.new'
import { Route as AuthenticatedMatchmakerIdRouteImport } from './routes/_authenticated/matchmaker.$id'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated/chat.$conversationId'
import { Route as ApiPublicHooksResetCallingQuotasRouteImport } from './routes/api/public/hooks/reset-calling-quotas'
import { Route as ApiPublicHooksKycCleanupRouteImport } from './routes/api/public/hooks/kyc-cleanup'
import { Route as AuthenticatedCallKindUserIdRouteImport } from './routes/_authenticated/call.$kind.$userId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferRoute = AuthenticatedReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecentsRoute = AuthenticatedRecentsRouteImport.update({
  id: '/recents',
  path: '/recents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationPreferencesRoute =
  AuthenticatedNotificationPreferencesRouteImport.update({
    id: '/notification-preferences',
    path: '/notification-preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewJoinersRoute = AuthenticatedNewJoinersRouteImport.update({
  id: '/new-joiners',
  path: '/new-joiners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDataExportRoute = AuthenticatedDataExportRouteImport.update({
  id: '/data-export',
  path: '/data-export',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatorDashboardRoute =
  AuthenticatedCreatorDashboardRouteImport.update({
    id: '/creator-dashboard',
    path: '/creator-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountDeleteRoute =
  AuthenticatedAccountDeleteRouteImport.update({
    id: '/account-delete',
    path: '/account-delete',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const _e2ePeerSheetBannerRoute = _e2ePeerSheetBannerRouteImport.update({
  id: '/__e2e/peer-sheet-banner',
  path: '/peer-sheet-banner',
  getParentRoute: () => rootRouteImport,
} as any)
const _e2eCallFullscreenRoute = _e2eCallFullscreenRouteImport.update({
  id: '/__e2e/call-fullscreen',
  path: '/call-fullscreen',
  getParentRoute: () => rootRouteImport,
} as any)
const _e2eCallControlsRoute = _e2eCallControlsRouteImport.update({
  id: '/__e2e/call-controls',
  path: '/call-controls',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const Call_e2ePeerSheetBannerRoute = Call_e2ePeerSheetBannerRouteImport.update({
  id: '/call/__e2e/peer-sheet-banner',
  path: '/call/peer-sheet-banner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRoomsNewRoute = AuthenticatedRoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsIdRoute = AuthenticatedRoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMysteryCaseIdRoute =
  AuthenticatedMysteryCaseIdRouteImport.update({
    id: '/mystery/$caseId',
    path: '/mystery/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchmakerNewRoute =
  AuthenticatedMatchmakerNewRouteImport.update({
    id: '/matchmaker/new',
    path: '/matchmaker/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchmakerIdRoute =
  AuthenticatedMatchmakerIdRouteImport.update({
    id: '/matchmaker/$id',
    path: '/matchmaker/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const ApiPublicHooksResetCallingQuotasRoute =
  ApiPublicHooksResetCallingQuotasRouteImport.update({
    id: '/api/public/hooks/reset-calling-quotas',
    path: '/api/public/hooks/reset-calling-quotas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKycCleanupRoute =
  ApiPublicHooksKycCleanupRouteImport.update({
    id: '/api/public/hooks/kyc-cleanup',
    path: '/api/public/hooks/kyc-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCallKindUserIdRoute =
  AuthenticatedCallKindUserIdRouteImport.update({
    id: '/call/$kind/$userId',
    path: '/call/$kind/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/banned': typeof BannedRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/delete-account': typeof DeleteAccountRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/call-controls': typeof _e2eCallControlsRoute
  '/call-fullscreen': typeof _e2eCallFullscreenRoute
  '/peer-sheet-banner': typeof _e2ePeerSheetBannerRoute
  '/account-delete': typeof AuthenticatedAccountDeleteRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/connect': typeof AuthenticatedConnectRoute
  '/creator-dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/data-export': typeof AuthenticatedDataExportRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/new-joiners': typeof AuthenticatedNewJoinersRoute
  '/notification-preferences': typeof AuthenticatedNotificationPreferencesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/recents': typeof AuthenticatedRecentsRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/refer': typeof AuthenticatedReferRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/matchmaker/$id': typeof AuthenticatedMatchmakerIdRoute
  '/matchmaker/new': typeof AuthenticatedMatchmakerNewRoute
  '/mystery/$caseId': typeof AuthenticatedMysteryCaseIdRoute
  '/rooms/$id': typeof AuthenticatedRoomsIdRoute
  '/rooms/new': typeof AuthenticatedRoomsNewRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/call/peer-sheet-banner': typeof Call_e2ePeerSheetBannerRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/call/$kind/$userId': typeof AuthenticatedCallKindUserIdRoute
  '/api/public/hooks/kyc-cleanup': typeof ApiPublicHooksKycCleanupRoute
  '/api/public/hooks/reset-calling-quotas': typeof ApiPublicHooksResetCallingQuotasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/banned': typeof BannedRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/delete-account': typeof DeleteAccountRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/call-controls': typeof _e2eCallControlsRoute
  '/call-fullscreen': typeof _e2eCallFullscreenRoute
  '/peer-sheet-banner': typeof _e2ePeerSheetBannerRoute
  '/account-delete': typeof AuthenticatedAccountDeleteRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/creator-dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/data-export': typeof AuthenticatedDataExportRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/new-joiners': typeof AuthenticatedNewJoinersRoute
  '/notification-preferences': typeof AuthenticatedNotificationPreferencesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/recents': typeof AuthenticatedRecentsRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/refer': typeof AuthenticatedReferRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/matchmaker/$id': typeof AuthenticatedMatchmakerIdRoute
  '/matchmaker/new': typeof AuthenticatedMatchmakerNewRoute
  '/mystery/$caseId': typeof AuthenticatedMysteryCaseIdRoute
  '/rooms/$id': typeof AuthenticatedRoomsIdRoute
  '/rooms/new': typeof AuthenticatedRoomsNewRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/call/peer-sheet-banner': typeof Call_e2ePeerSheetBannerRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/call/$kind/$userId': typeof AuthenticatedCallKindUserIdRoute
  '/api/public/hooks/kyc-cleanup': typeof ApiPublicHooksKycCleanupRoute
  '/api/public/hooks/reset-calling-quotas': typeof ApiPublicHooksResetCallingQuotasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/banned': typeof BannedRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/delete-account': typeof DeleteAccountRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/__e2e/call-controls': typeof _e2eCallControlsRoute
  '/__e2e/call-fullscreen': typeof _e2eCallFullscreenRoute
  '/__e2e/peer-sheet-banner': typeof _e2ePeerSheetBannerRoute
  '/_authenticated/account-delete': typeof AuthenticatedAccountDeleteRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/creator-dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/_authenticated/data-export': typeof AuthenticatedDataExportRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/new-joiners': typeof AuthenticatedNewJoinersRoute
  '/_authenticated/notification-preferences': typeof AuthenticatedNotificationPreferencesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/recents': typeof AuthenticatedRecentsRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/refer': typeof AuthenticatedReferRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/matchmaker/$id': typeof AuthenticatedMatchmakerIdRoute
  '/_authenticated/matchmaker/new': typeof AuthenticatedMatchmakerNewRoute
  '/_authenticated/mystery/$caseId': typeof AuthenticatedMysteryCaseIdRoute
  '/_authenticated/rooms/$id': typeof AuthenticatedRoomsIdRoute
  '/_authenticated/rooms/new': typeof AuthenticatedRoomsNewRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/call/__e2e/peer-sheet-banner': typeof Call_e2ePeerSheetBannerRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/call/$kind/$userId': typeof AuthenticatedCallKindUserIdRoute
  '/api/public/hooks/kyc-cleanup': typeof ApiPublicHooksKycCleanupRoute
  '/api/public/hooks/reset-calling-quotas': typeof ApiPublicHooksResetCallingQuotasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/banned'
    | '/community-guidelines'
    | '/delete-account'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/refund-policy'
    | '/safety'
    | '/terms'
    | '/call-controls'
    | '/call-fullscreen'
    | '/peer-sheet-banner'
    | '/account-delete'
    | '/admin'
    | '/chat'
    | '/connect'
    | '/creator-dashboard'
    | '/data-export'
    | '/diagnostics'
    | '/home'
    | '/leaderboard'
    | '/new-joiners'
    | '/notification-preferences'
    | '/notifications'
    | '/onboarding'
    | '/recents'
    | '/recharge'
    | '/refer'
    | '/requests'
    | '/settings'
    | '/wallet'
    | '/withdraw'
    | '/chat/$conversationId'
    | '/matchmaker/$id'
    | '/matchmaker/new'
    | '/mystery/$caseId'
    | '/rooms/$id'
    | '/rooms/new'
    | '/api/public/razorpay-webhook'
    | '/call/peer-sheet-banner'
    | '/admin/'
    | '/chat/'
    | '/call/$kind/$userId'
    | '/api/public/hooks/kyc-cleanup'
    | '/api/public/hooks/reset-calling-quotas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/banned'
    | '/community-guidelines'
    | '/delete-account'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/refund-policy'
    | '/safety'
    | '/terms'
    | '/call-controls'
    | '/call-fullscreen'
    | '/peer-sheet-banner'
    | '/account-delete'
    | '/connect'
    | '/creator-dashboard'
    | '/data-export'
    | '/diagnostics'
    | '/home'
    | '/leaderboard'
    | '/new-joiners'
    | '/notification-preferences'
    | '/notifications'
    | '/onboarding'
    | '/recents'
    | '/recharge'
    | '/refer'
    | '/requests'
    | '/settings'
    | '/wallet'
    | '/withdraw'
    | '/chat/$conversationId'
    | '/matchmaker/$id'
    | '/matchmaker/new'
    | '/mystery/$caseId'
    | '/rooms/$id'
    | '/rooms/new'
    | '/api/public/razorpay-webhook'
    | '/call/peer-sheet-banner'
    | '/admin'
    | '/chat'
    | '/call/$kind/$userId'
    | '/api/public/hooks/kyc-cleanup'
    | '/api/public/hooks/reset-calling-quotas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/banned'
    | '/community-guidelines'
    | '/delete-account'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/refund-policy'
    | '/safety'
    | '/terms'
    | '/__e2e/call-controls'
    | '/__e2e/call-fullscreen'
    | '/__e2e/peer-sheet-banner'
    | '/_authenticated/account-delete'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/connect'
    | '/_authenticated/creator-dashboard'
    | '/_authenticated/data-export'
    | '/_authenticated/diagnostics'
    | '/_authenticated/home'
    | '/_authenticated/leaderboard'
    | '/_authenticated/new-joiners'
    | '/_authenticated/notification-preferences'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/recents'
    | '/_authenticated/recharge'
    | '/_authenticated/refer'
    | '/_authenticated/requests'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/matchmaker/$id'
    | '/_authenticated/matchmaker/new'
    | '/_authenticated/mystery/$caseId'
    | '/_authenticated/rooms/$id'
    | '/_authenticated/rooms/new'
    | '/api/public/razorpay-webhook'
    | '/call/__e2e/peer-sheet-banner'
    | '/_authenticated/admin/'
    | '/_authenticated/chat/'
    | '/_authenticated/call/$kind/$userId'
    | '/api/public/hooks/kyc-cleanup'
    | '/api/public/hooks/reset-calling-quotas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BannedRoute: typeof BannedRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SafetyRoute: typeof SafetyRoute
  TermsRoute: typeof TermsRoute
  _e2eCallControlsRoute: typeof _e2eCallControlsRoute
  _e2eCallFullscreenRoute: typeof _e2eCallFullscreenRoute
  _e2ePeerSheetBannerRoute: typeof _e2ePeerSheetBannerRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  Call_e2ePeerSheetBannerRoute: typeof Call_e2ePeerSheetBannerRoute
  ApiPublicHooksKycCleanupRoute: typeof ApiPublicHooksKycCleanupRoute
  ApiPublicHooksResetCallingQuotasRoute: typeof ApiPublicHooksResetCallingQuotasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refer': {
      id: '/_authenticated/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof AuthenticatedReferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recents': {
      id: '/_authenticated/recents'
      path: '/recents'
      fullPath: '/recents'
      preLoaderRoute: typeof AuthenticatedRecentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-preferences': {
      id: '/_authenticated/notification-preferences'
      path: '/notification-preferences'
      fullPath: '/notification-preferences'
      preLoaderRoute: typeof AuthenticatedNotificationPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-joiners': {
      id: '/_authenticated/new-joiners'
      path: '/new-joiners'
      fullPath: '/new-joiners'
      preLoaderRoute: typeof AuthenticatedNewJoinersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-export': {
      id: '/_authenticated/data-export'
      path: '/data-export'
      fullPath: '/data-export'
      preLoaderRoute: typeof AuthenticatedDataExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator-dashboard': {
      id: '/_authenticated/creator-dashboard'
      path: '/creator-dashboard'
      fullPath: '/creator-dashboard'
      preLoaderRoute: typeof AuthenticatedCreatorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-delete': {
      id: '/_authenticated/account-delete'
      path: '/account-delete'
      fullPath: '/account-delete'
      preLoaderRoute: typeof AuthenticatedAccountDeleteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/__e2e/peer-sheet-banner': {
      id: '/__e2e/peer-sheet-banner'
      path: '/peer-sheet-banner'
      fullPath: '/peer-sheet-banner'
      preLoaderRoute: typeof _e2ePeerSheetBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__e2e/call-fullscreen': {
      id: '/__e2e/call-fullscreen'
      path: '/call-fullscreen'
      fullPath: '/call-fullscreen'
      preLoaderRoute: typeof _e2eCallFullscreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__e2e/call-controls': {
      id: '/__e2e/call-controls'
      path: '/call-controls'
      fullPath: '/call-controls'
      preLoaderRoute: typeof _e2eCallControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/call/__e2e/peer-sheet-banner': {
      id: '/call/__e2e/peer-sheet-banner'
      path: '/call/peer-sheet-banner'
      fullPath: '/call/peer-sheet-banner'
      preLoaderRoute: typeof Call_e2ePeerSheetBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms/new': {
      id: '/_authenticated/rooms/new'
      path: '/rooms/new'
      fullPath: '/rooms/new'
      preLoaderRoute: typeof AuthenticatedRoomsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms/$id': {
      id: '/_authenticated/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof AuthenticatedRoomsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mystery/$caseId': {
      id: '/_authenticated/mystery/$caseId'
      path: '/mystery/$caseId'
      fullPath: '/mystery/$caseId'
      preLoaderRoute: typeof AuthenticatedMysteryCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchmaker/new': {
      id: '/_authenticated/matchmaker/new'
      path: '/matchmaker/new'
      fullPath: '/matchmaker/new'
      preLoaderRoute: typeof AuthenticatedMatchmakerNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchmaker/$id': {
      id: '/_authenticated/matchmaker/$id'
      path: '/matchmaker/$id'
      fullPath: '/matchmaker/$id'
      preLoaderRoute: typeof AuthenticatedMatchmakerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/public/hooks/reset-calling-quotas': {
      id: '/api/public/hooks/reset-calling-quotas'
      path: '/api/public/hooks/reset-calling-quotas'
      fullPath: '/api/public/hooks/reset-calling-quotas'
      preLoaderRoute: typeof ApiPublicHooksResetCallingQuotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/kyc-cleanup': {
      id: '/api/public/hooks/kyc-cleanup'
      path: '/api/public/hooks/kyc-cleanup'
      fullPath: '/api/public/hooks/kyc-cleanup'
      preLoaderRoute: typeof ApiPublicHooksKycCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/call/$kind/$userId': {
      id: '/_authenticated/call/$kind/$userId'
      path: '/call/$kind/$userId'
      fullPath: '/call/$kind/$userId'
      preLoaderRoute: typeof AuthenticatedCallKindUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountDeleteRoute: typeof AuthenticatedAccountDeleteRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedCreatorDashboardRoute: typeof AuthenticatedCreatorDashboardRoute
  AuthenticatedDataExportRoute: typeof AuthenticatedDataExportRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNewJoinersRoute: typeof AuthenticatedNewJoinersRoute
  AuthenticatedNotificationPreferencesRoute: typeof AuthenticatedNotificationPreferencesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRecentsRoute: typeof AuthenticatedRecentsRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedReferRoute: typeof AuthenticatedReferRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedMatchmakerIdRoute: typeof AuthenticatedMatchmakerIdRoute
  AuthenticatedMatchmakerNewRoute: typeof AuthenticatedMatchmakerNewRoute
  AuthenticatedMysteryCaseIdRoute: typeof AuthenticatedMysteryCaseIdRoute
  AuthenticatedRoomsIdRoute: typeof AuthenticatedRoomsIdRoute
  AuthenticatedRoomsNewRoute: typeof AuthenticatedRoomsNewRoute
  AuthenticatedCallKindUserIdRoute: typeof AuthenticatedCallKindUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountDeleteRoute: AuthenticatedAccountDeleteRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedCreatorDashboardRoute: AuthenticatedCreatorDashboardRoute,
  AuthenticatedDataExportRoute: AuthenticatedDataExportRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNewJoinersRoute: AuthenticatedNewJoinersRoute,
  AuthenticatedNotificationPreferencesRoute:
    AuthenticatedNotificationPreferencesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRecentsRoute: AuthenticatedRecentsRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedReferRoute: AuthenticatedReferRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
  AuthenticatedMatchmakerIdRoute: AuthenticatedMatchmakerIdRoute,
  AuthenticatedMatchmakerNewRoute: AuthenticatedMatchmakerNewRoute,
  AuthenticatedMysteryCaseIdRoute: AuthenticatedMysteryCaseIdRoute,
  AuthenticatedRoomsIdRoute: AuthenticatedRoomsIdRoute,
  AuthenticatedRoomsNewRoute: AuthenticatedRoomsNewRoute,
  AuthenticatedCallKindUserIdRoute: AuthenticatedCallKindUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BannedRoute: BannedRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SafetyRoute: SafetyRoute,
  TermsRoute: TermsRoute,
  _e2eCallControlsRoute: _e2eCallControlsRoute,
  _e2eCallFullscreenRoute: _e2eCallFullscreenRoute,
  _e2ePeerSheetBannerRoute: _e2ePeerSheetBannerRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  Call_e2ePeerSheetBannerRoute: Call_e2ePeerSheetBannerRoute,
  ApiPublicHooksKycCleanupRoute: ApiPublicHooksKycCleanupRoute,
  ApiPublicHooksResetCallingQuotasRoute: ApiPublicHooksResetCallingQuotasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
